default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: laba42_development

test:
  <<: *default
  database: laba42_test

production:
  <<: *default
  database: laba42_production
  username: laba42
  password: <%= ENV['LABA42_DATABASE_PASSWORD'] %>
